### PR TITLE
Use markdown table

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
We'd already used [fluent-plugin-config-format](https://github.com/fluent/fluentd/blob/master/lib/fluent/command/plugin_config_formatter.rb) like format on README.
Could you try to add markdown table style dumping functionality in fluent-plugin-config-format?

**Comment by kenhys** [comment]
I've sent PR fluent-pugin-config-format.
https://github.com/fluent/fluentd/pull/3240

**Review by cosmo0920 — APPROVED** [review]
I'd reviewed a PR: https://github.com/fluent/fluentd/pull/3240
Looks good to me. :+1:

**Comment by cosmo0920** [comment]
@kenhys Could you add `desc` method for each parameter? Currently, there is no `desc` in this plugin.

**Comment by kenhys** [comment]
Ok, I'll do it.

**Pull request merged**
