### PR TITLE
CI: migrate Travis-CI to GitHub Actions

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
Need to fix for 3.0.

**Review by cosmo0920 — APPROVED** [review]
This PR is needed to fix testing failure on Ruby 3.0 development.
LGTM.

**Comment by kenhys** [comment]
Fixed missing gem issue and now ready.
https://github.com/kenhys/fluent-plugin-kv-parser/actions

**Comment by cosmo0920** [comment]
@kenhys Could you send a PR to replace travis-ci badge with GitHub Actions' ones?

**Comment by kenhys** [comment]
Ok, I'll do it.

**Pull request merged**
